import Head from "next/head";
import React from "react";
import 'semantic-ui-css/semantic.min.css'

export default function Login() {

    return (
        <div>
            <Head>
                <title>GAuth | LOGIN</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="ui centered grid" style={{ paddingTop: 200 }}>
                <div style={{ width: 450 }}>
                    <div className="ui middle aligned center aligned grid">
                        <div className="column">
                            <h2 className="ui teal image header">
                                <img src="https://semantic-ui.com/examples/assets/images/logo.png" className="image" />
                                <div className="content">
                                    Log-in to your account
                                </div>
                            </h2>
                            <form className="ui large form">
                                <div className="ui stacked segment">
                                    <div className="field">
                                        <div className="ui left icon input">
                                            <i className="user icon"></i>
                                            <input type="text" name="email" placeholder="E-mail address" />
                                        </div>
                                    </div>
                                    <div className="field">
                                        <div className="ui left icon input">
                                            <i className="lock icon"></i>
                                            <input type="password" name="password" placeholder="Password" />
                                        </div>
                                    </div>
                                    <div className="ui fluid large teal submit button">Login</div>
                                </div>
                                <div className="ui error message"></div>
                            </form>
                            <div className="ui message">
                                New to us? <a href="/auth/signup">Sign Up</a>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
            <footer>

            </footer>
        </div>
    )
}